services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

  api:
    image: rowmate-v2-backend
    build: https://github.com/rowmateproject/rowmate-v2-backend.git#main
    working_dir: /rowmate-backend
    environment:
      DATABASE_URL: mongodb://mongodb:27017
    ports:
      - "8081:80"
    depends_on:
      - mongodb
    networks:
      - backend
      - public
    labels:
      - traefik.http.routers.api.rule=Host(`api.dev.rowmate.org`)
      - traefik.http.services.api.loadbalancer.server.port=8081

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    image: rowmate-v2-frontend
    build: https://github.com/rowmateproject/rowmate-v2-frontend.git
    ports:
      - "8082:8080"
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.dev.rowmate.org`)"
      - "traefik.http.routers.app.entrypoints=web"

volumes:
  mongodb_data_container:
networks:
  backend:
  public:
