services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend


  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=app@rowmate.org"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      
    labels:
      - "traefik.http.middlewares.to-https.redirectscheme.scheme=https"
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.to-https.entrypoints=http
      - traefik.http.routers.to-https.middlewares=to-https

      - traefik.http.routers.traefik.rule=Host(`traefik.dev.rowmate.org`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt

    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
    networks:
      - public


  frontend:
    image: rowmate-v2-frontend
    build: https://github.com/rowmateproject/rowmate-v2-frontend.git
    ports:
      - "8082:8080"
    networks:
      - public
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.dev.rowmate.org`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app.tls=true"

  api:
    image: rowmate-v2-backend
    build: https://github.com/rowmateproject/rowmate-v2-backend.git#main
    working_dir: /rowmate-backend
    environment:
      DATABASE_URL: mongodb://mongodb:27017
    ports:
      - "8081:80"
    depends_on:
      - mongodb
      - traefik
    networks:
      - backend
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.dev.rowmate.org`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.tls=true"

volumes:
  mongodb_data_container:
networks:
  backend:
  public:
